version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: nest-default-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: nest
    volumes:
      - data-volume:/data/db
volumes:
  data-volume: